" vim:fdm=marker:fmr={{{,}}}:fdl=1:ts=4:sts=2:sw=2:ft=vim

if has('vim_starting') " {{{
  if &compatible
    set nocompatible
  endif

  set all&
endif " }}}


" Neovim detection
set runtimepath^=$XDG_CONFIG_HOME/vim runtimepath+=$XDG_CONFIG_HOME/vim/after
let &packpath = &runtimepath


" Options
let g:nerdfont = 0


" Load Plugins {{{
call plug#extentions#disable_buildin()

call plug#begin('$XDG_CACHE_HOME/vim/plugged')
  source $XDG_CONFIG_HOME/vim/plugs.vim
call plug#end()

" Enable plugin system
filetype plugin indent on
syntax enable

" Download plugins on fresh install
if empty(glob('$XDG_CACHE_HOME/vim/plugged'))
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" }}}


set background=dark
silent! colorscheme onedark
