" vim:fdm=marker:fmr={{{,}}}:fdl=1:ts=4:sts=2:sw=2:ft=vim

if has('vim_starting') " {{{
  if &compatible
    set nocompatible
  endif

  set all&
endif " }}}


" Load Plugins {{{
call plug#extentions#disable_buildin()

call plug#begin('~/.cache/plugged')
  source ~/.vim/plugs.vim
call plug#end()

" Enable plugin system
filetype plugin indent on
syntax enable
" }}}


set background=dark
colorscheme one
